# Generated by Django 5.2.16 on 2026-07-31 14:40

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
  initial = True

  dependencies = [
    ("core", "0001_initial"),
    migrations.swappable_dependency(settings.AUTH_USER_MODEL),
  ]

  operations = [
    migrations.CreateModel(
      name="CandidateProfile",
      fields=[
        (
          "id",
          models.UUIDField(
            default=uuid.uuid4, editable=False, primary_key=True, serialize=False
          ),
        ),
        ("first_name", models.CharField(blank=True, max_length=100)),
        ("last_name", models.CharField(blank=True, max_length=100)),
        ("bio", models.TextField(blank=True)),
        ("photo_url", models.URLField(blank=True)),
        ("cv_url", models.URLField(blank=True)),
        ("profile_completion", models.PositiveSmallIntegerField(default=0)),
        ("is_expert_profile", models.BooleanField(default=False)),
        ("actively_looking", models.BooleanField(default=False)),
        ("created_at", models.DateTimeField(auto_now_add=True)),
        ("updated_at", models.DateTimeField(auto_now=True)),
        (
          "user",
          models.OneToOneField(
            on_delete=django.db.models.deletion.CASCADE,
            related_name="candidate_profile",
            to=settings.AUTH_USER_MODEL,
          ),
        ),
      ],
    ),
    migrations.CreateModel(
      name="DesiredPosition",
      fields=[
        (
          "id",
          models.UUIDField(
            default=uuid.uuid4, editable=False, primary_key=True, serialize=False
          ),
        ),
        ("engagement_types", models.JSONField(blank=True, default=list)),
        ("modalities", models.JSONField(blank=True, default=list)),
        (
          "availability",
          models.CharField(
            blank=True,
            choices=[
              ("full_time", "Full-time"),
              ("part_time", "Part-time"),
              ("occasional", "Occasional"),
              ("evenings", "Evenings"),
              ("weekends", "Weekends"),
            ],
            max_length=20,
          ),
        ),
        (
          "mobility",
          models.CharField(
            blank=True,
            choices=[
              ("local", "Local"),
              ("regional", "Regional"),
              ("national", "National"),
              ("international", "International"),
              ("field", "Field"),
            ],
            max_length=20,
          ),
        ),
        (
          "position_level",
          models.CharField(
            blank=True,
            choices=[
              ("junior", "Junior"),
              ("confirmed", "Confirmed"),
              ("senior", "Senior"),
              ("expert", "Expert"),
              ("mandate", "Mandate"),
            ],
            max_length=20,
          ),
        ),
        (
          "min_daily_rate",
          models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        ("available_from", models.DateField(blank=True, null=True)),
        ("available_until", models.DateField(blank=True, null=True)),
        ("created_at", models.DateTimeField(auto_now_add=True)),
        ("updated_at", models.DateTimeField(auto_now=True)),
        (
          "candidate",
          models.OneToOneField(
            on_delete=django.db.models.deletion.CASCADE,
            related_name="desired_position",
            to="candidates.candidateprofile",
          ),
        ),
        (
          "excluded_causes",
          models.ManyToManyField(
            blank=True, related_name="excluded_by_candidates", to="core.cause"
          ),
        ),
        (
          "preferred_causes",
          models.ManyToManyField(
            blank=True, related_name="desired_by_candidates", to="core.cause"
          ),
        ),
        (
          "preferred_geographies",
          models.ManyToManyField(
            blank=True, related_name="desired_by_candidates", to="core.country"
          ),
        ),
        (
          "skills_to_develop",
          models.ManyToManyField(
            blank=True, related_name="developed_by_candidates", to="core.skill"
          ),
        ),
        (
          "skills_to_leverage",
          models.ManyToManyField(
            blank=True, related_name="leveraged_by_candidates", to="core.skill"
          ),
        ),
      ],
    ),
  ]
