# Generated by Django 5.2.16 on 2026-08-15 11:35

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
  dependencies = [
    ("candidates", "0001_initial"),
    ("organizations", "0001_initial"),
  ]

  operations = [
    migrations.CreateModel(
      name="Application",
      fields=[
        (
          "id",
          models.UUIDField(
            default=uuid.uuid4, editable=False, primary_key=True, serialize=False
          ),
        ),
        (
          "stage",
          models.CharField(
            choices=[
              ("submitted", "Submitted"),
              ("prequalified", "Prequalified"),
              ("interview", "Interview"),
              ("decision", "Decision"),
              ("offer", "Offer"),
            ],
            default="submitted",
            max_length=20,
          ),
        ),
        ("created_at", models.DateTimeField(auto_now_add=True)),
        ("updated_at", models.DateTimeField(auto_now=True)),
        (
          "candidate",
          models.ForeignKey(
            on_delete=django.db.models.deletion.CASCADE,
            related_name="applications",
            to="candidates.candidateprofile",
          ),
        ),
        (
          "offer",
          models.ForeignKey(
            on_delete=django.db.models.deletion.CASCADE,
            related_name="applications",
            to="organizations.offer",
          ),
        ),
      ],
      options={
        "ordering": ["-updated_at"],
      },
    ),
  ]
