# Generated by Django 5.2.16 on 2026-08-15 11:37

from django.db import migrations, models


class Migration(migrations.Migration):
  dependencies = [
    ("candidates", "0002_application"),
  ]

  operations = [
    migrations.AddField(
      model_name="desiredposition",
      name="email_alerts",
      field=models.BooleanField(default=False),
    ),
    migrations.AddField(
      model_name="desiredposition",
      name="position_title",
      field=models.CharField(blank=True, max_length=120),
    ),
  ]
