# Generated by Django 5.2.16 on 2026-07-29 01:30

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
  initial = True

  dependencies = []

  operations = [
    migrations.CreateModel(
      name="User",
      fields=[
        ("password", models.CharField(max_length=128, verbose_name="password")),
        (
          "last_login",
          models.DateTimeField(blank=True, null=True, verbose_name="last login"),
        ),
        (
          "id",
          models.UUIDField(
            default=uuid.uuid4, editable=False, primary_key=True, serialize=False
          ),
        ),
        (
          "email",
          models.EmailField(max_length=254, unique=True, verbose_name="email address"),
        ),
        (
          "auth_provider",
          models.CharField(
            choices=[
              ("email", "Email"),
              ("google", "Google"),
              ("linkedin", "LinkedIn"),
              ("apple", "Apple"),
            ],
            default="email",
            max_length=20,
          ),
        ),
        ("external_auth_id", models.CharField(blank=True, max_length=255, null=True)),
        ("email_verified", models.BooleanField(default=False)),
        ("phone", models.CharField(blank=True, max_length=20, null=True)),
        ("phone_verified", models.BooleanField(default=False)),
        (
          "role",
          models.CharField(
            choices=[
              ("candidate", "Candidate"),
              ("ngo_member", "NGO Member"),
              ("volunteering_referent", "Volunteering Referent"),
              ("admin", "Admin"),
              ("moderator", "Moderator"),
            ],
            default="candidate",
            max_length=30,
          ),
        ),
        (
          "status",
          models.CharField(
            choices=[
              ("active", "Active"),
              ("suspended", "Suspended"),
              ("banned", "Banned"),
              ("pending", "Pending"),
            ],
            default="pending",
            max_length=20,
          ),
        ),
        ("notification_prefs", models.JSONField(blank=True, default=dict)),
        ("created_at", models.DateTimeField(auto_now_add=True)),
        ("updated_at", models.DateTimeField(auto_now=True)),
      ],
      options={
        "abstract": False,
      },
    ),
  ]
