# Generated by Django 5.2.16 on 2026-07-29 14:21

import uuid

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
  initial = True

  dependencies = [
    migrations.swappable_dependency(settings.AUTH_USER_MODEL),
  ]

  operations = [
    migrations.CreateModel(
      name="Cause",
      fields=[
        (
          "id",
          models.BigAutoField(
            auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
          ),
        ),
        ("name", models.CharField(max_length=120)),
        ("slug", models.SlugField(unique=True)),
        ("is_active", models.BooleanField(default=True)),
      ],
      options={
        "ordering": ["name"],
      },
    ),
    migrations.CreateModel(
      name="Country",
      fields=[
        ("code", models.CharField(max_length=2, primary_key=True, serialize=False)),
        ("name_fr", models.CharField(max_length=120)),
        ("is_covered", models.BooleanField(default=True)),
        ("sort_order", models.PositiveIntegerField(default=100)),
      ],
      options={
        "ordering": ["sort_order", "name_fr"],
      },
    ),
    migrations.CreateModel(
      name="Language",
      fields=[
        (
          "id",
          models.BigAutoField(
            auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
          ),
        ),
        ("code", models.CharField(max_length=10, unique=True)),
        ("name_fr", models.CharField(max_length=120)),
        ("is_active", models.BooleanField(default=True)),
      ],
      options={
        "ordering": ["name_fr"],
      },
    ),
    migrations.CreateModel(
      name="Skill",
      fields=[
        (
          "id",
          models.BigAutoField(
            auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
          ),
        ),
        ("name", models.CharField(max_length=120)),
        ("slug", models.SlugField(unique=True)),
        ("is_active", models.BooleanField(default=True)),
      ],
      options={
        "ordering": ["name"],
      },
    ),
    migrations.CreateModel(
      name="SponsorSlot",
      fields=[
        (
          "id",
          models.BigAutoField(
            auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
          ),
        ),
        ("created_at", models.DateTimeField(auto_now_add=True)),
        ("updated_at", models.DateTimeField(auto_now=True)),
        ("placement", models.CharField(max_length=80)),
        ("sponsor_name", models.CharField(max_length=180)),
        ("label", models.CharField(blank=True, max_length=80)),
        ("copy", models.TextField(blank=True)),
        ("target_url", models.URLField(blank=True)),
        ("starts_at", models.DateTimeField(default=django.utils.timezone.now)),
        ("ends_at", models.DateTimeField(blank=True, null=True)),
        ("is_active", models.BooleanField(default=True)),
      ],
      options={
        "abstract": False,
      },
    ),
    migrations.CreateModel(
      name="Offer",
      fields=[
        ("created_at", models.DateTimeField(auto_now_add=True)),
        ("updated_at", models.DateTimeField(auto_now=True)),
        (
          "id",
          models.UUIDField(
            default=uuid.uuid4, editable=False, primary_key=True, serialize=False
          ),
        ),
        ("title", models.CharField(max_length=180)),
        ("slug", models.SlugField(blank=True, unique=True)),
        (
          "engagement_type",
          models.CharField(
            choices=[
              ("employment", "Employment"),
              ("volunteering", "Volunteering"),
              ("skills_sponsorship", "Skills sponsorship"),
              ("governance", "Governance"),
              ("consulting", "Consulting"),
              ("freelance", "Freelance"),
            ],
            max_length=40,
          ),
        ),
        ("employment_contract", models.CharField(blank=True, max_length=40)),
        ("city", models.CharField(blank=True, max_length=120)),
        ("region", models.CharField(blank=True, max_length=120)),
        (
          "remote_mode",
          models.CharField(
            choices=[
              ("on_site", "On site"),
              ("hybrid", "Hybrid"),
              ("remote", "Remote"),
            ],
            default="on_site",
            max_length=40,
          ),
        ),
        ("description", models.TextField()),
        ("responsibilities", models.TextField(blank=True)),
        ("desired_profile", models.TextField(blank=True)),
        ("conditions", models.TextField(blank=True)),
        ("duration_label", models.CharField(blank=True, max_length=120)),
        ("duration_days", models.PositiveIntegerField(blank=True, null=True)),
        ("experience_level", models.CharField(blank=True, max_length=40)),
        (
          "status",
          models.CharField(
            choices=[
              ("draft", "Draft"),
              ("published", "Published"),
              ("closed", "Closed"),
            ],
            default="published",
            max_length=40,
          ),
        ),
        ("published_at", models.DateTimeField(default=django.utils.timezone.now)),
        ("expires_at", models.DateTimeField(blank=True, null=True)),
        ("featured", models.BooleanField(default=False)),
        ("views_count", models.PositiveIntegerField(default=0)),
        (
          "causes",
          models.ManyToManyField(
            blank=True, related_name="offers", to="engagement.cause"
          ),
        ),
        (
          "country",
          models.ForeignKey(
            on_delete=django.db.models.deletion.PROTECT,
            related_name="offers",
            to="engagement.country",
          ),
        ),
        (
          "languages",
          models.ManyToManyField(
            blank=True, related_name="offers", to="engagement.language"
          ),
        ),
      ],
      options={
        "ordering": ["-featured", "-published_at"],
      },
    ),
    migrations.CreateModel(
      name="OfferEvent",
      fields=[
        (
          "id",
          models.BigAutoField(
            auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
          ),
        ),
        ("created_at", models.DateTimeField(auto_now_add=True)),
        ("updated_at", models.DateTimeField(auto_now=True)),
        ("event_type", models.CharField(max_length=40)),
        ("channel", models.CharField(blank=True, max_length=40)),
        ("ip_hash", models.CharField(blank=True, max_length=64)),
        ("user_agent_hash", models.CharField(blank=True, max_length=64)),
        (
          "offer",
          models.ForeignKey(
            on_delete=django.db.models.deletion.CASCADE,
            related_name="events",
            to="engagement.offer",
          ),
        ),
        (
          "user",
          models.ForeignKey(
            blank=True,
            null=True,
            on_delete=django.db.models.deletion.SET_NULL,
            to=settings.AUTH_USER_MODEL,
          ),
        ),
      ],
      options={
        "abstract": False,
      },
    ),
    migrations.CreateModel(
      name="Organization",
      fields=[
        ("created_at", models.DateTimeField(auto_now_add=True)),
        ("updated_at", models.DateTimeField(auto_now=True)),
        (
          "id",
          models.UUIDField(
            default=uuid.uuid4, editable=False, primary_key=True, serialize=False
          ),
        ),
        ("name", models.CharField(max_length=180)),
        ("slug", models.SlugField(blank=True, unique=True)),
        ("type", models.CharField(max_length=40)),
        ("city", models.CharField(max_length=120)),
        ("registry_number", models.CharField(blank=True, max_length=120)),
        ("size", models.CharField(blank=True, max_length=40)),
        ("description", models.TextField()),
        ("mission", models.TextField(blank=True)),
        ("website", models.URLField(blank=True)),
        (
          "verification_status",
          models.CharField(
            choices=[
              ("pending", "Pending"),
              ("verified", "Verified"),
              ("certified_plus", "Certified plus"),
            ],
            default="pending",
            max_length=40,
          ),
        ),
        ("is_active", models.BooleanField(default=True)),
        (
          "causes",
          models.ManyToManyField(
            blank=True, related_name="organizations", to="engagement.cause"
          ),
        ),
        (
          "country",
          models.ForeignKey(
            on_delete=django.db.models.deletion.PROTECT,
            related_name="organizations",
            to="engagement.country",
          ),
        ),
        (
          "owner",
          models.ForeignKey(
            on_delete=django.db.models.deletion.CASCADE,
            related_name="engagement_organizations",
            to=settings.AUTH_USER_MODEL,
          ),
        ),
      ],
      options={
        "ordering": ["name"],
      },
    ),
    migrations.AddField(
      model_name="offer",
      name="organization",
      field=models.ForeignKey(
        on_delete=django.db.models.deletion.CASCADE,
        related_name="offers",
        to="engagement.organization",
      ),
    ),
    migrations.AddField(
      model_name="offer",
      name="skills",
      field=models.ManyToManyField(
        blank=True, related_name="offers", to="engagement.skill"
      ),
    ),
    migrations.CreateModel(
      name="SponsorshipMission",
      fields=[
        ("created_at", models.DateTimeField(auto_now_add=True)),
        ("updated_at", models.DateTimeField(auto_now=True)),
        (
          "id",
          models.UUIDField(
            default=uuid.uuid4, editable=False, primary_key=True, serialize=False
          ),
        ),
        (
          "tracking_uuid",
          models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        ("contact_email", models.EmailField(max_length=254)),
        ("company_name", models.CharField(max_length=180)),
        ("company_legal_id", models.CharField(blank=True, max_length=120)),
        ("region", models.CharField(blank=True, max_length=120)),
        ("title", models.CharField(max_length=180)),
        ("description", models.TextField(blank=True)),
        ("objectives", models.TextField(blank=True)),
        ("deliverables", models.TextField(blank=True)),
        ("required_profiles", models.TextField(blank=True)),
        ("man_days", models.PositiveIntegerField()),
        (
          "visibility",
          models.CharField(
            choices=[
              ("open", "Open"),
              ("verified_organizations", "Verified organizations"),
            ],
            max_length=40,
          ),
        ),
        (
          "status",
          models.CharField(
            choices=[
              ("pending_email_verification", "Pending email verification"),
              ("submitted", "Submitted"),
            ],
            default="pending_email_verification",
            max_length=40,
          ),
        ),
        ("verification_token_hash", models.CharField(max_length=64)),
        ("verified_email_at", models.DateTimeField(blank=True, null=True)),
        (
          "causes",
          models.ManyToManyField(
            blank=True, related_name="sponsorship_missions", to="engagement.cause"
          ),
        ),
        (
          "country",
          models.ForeignKey(
            blank=True,
            null=True,
            on_delete=django.db.models.deletion.SET_NULL,
            to="engagement.country",
          ),
        ),
      ],
      options={
        "abstract": False,
      },
    ),
    migrations.CreateModel(
      name="Application",
      fields=[
        (
          "id",
          models.BigAutoField(
            auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
          ),
        ),
        ("created_at", models.DateTimeField(auto_now_add=True)),
        ("updated_at", models.DateTimeField(auto_now=True)),
        ("cover_letter", models.TextField(blank=True)),
        ("status", models.CharField(default="new", max_length=40)),
        ("applied_at", models.DateTimeField(default=django.utils.timezone.now)),
        (
          "candidate",
          models.ForeignKey(
            on_delete=django.db.models.deletion.CASCADE,
            related_name="applications",
            to=settings.AUTH_USER_MODEL,
          ),
        ),
        (
          "offer",
          models.ForeignKey(
            on_delete=django.db.models.deletion.CASCADE,
            related_name="applications",
            to="engagement.offer",
          ),
        ),
      ],
      options={
        "unique_together": {("offer", "candidate")},
      },
    ),
    migrations.CreateModel(
      name="SavedOffer",
      fields=[
        (
          "id",
          models.BigAutoField(
            auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
          ),
        ),
        ("created_at", models.DateTimeField(auto_now_add=True)),
        ("updated_at", models.DateTimeField(auto_now=True)),
        (
          "offer",
          models.ForeignKey(
            on_delete=django.db.models.deletion.CASCADE,
            related_name="saved_by",
            to="engagement.offer",
          ),
        ),
        (
          "user",
          models.ForeignKey(
            on_delete=django.db.models.deletion.CASCADE,
            related_name="saved_offers",
            to=settings.AUTH_USER_MODEL,
          ),
        ),
      ],
      options={
        "unique_together": {("offer", "user")},
      },
    ),
  ]
